project_id = "otsmjgrhyteyvpufkwdh"

[auth]
site_url = "http://localhost:5173"

[functions.generate-path]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.transcribe-lecture]
verify_jwt = true

[functions.generate-lecture-questions]
verify_jwt = true

[functions.auto-grade-short-answer]
verify_jwt = true

[functions.generate-course-questions]
verify_jwt = true

[functions.parse-lecture-material]
verify_jwt = true