project_id = "otsmjgrhyteyvpufkwdh"

[auth]
site_url = "http://localhost:5173"

[functions.generate-path]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.transcribe-lecture]
verify_jwt = true

[functions.generate-lecture-questions]
verify_jwt = true